pipeline {
    agent any
    tools { 
      maven 'jenkins-maven'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/HaHust/jenkins-maven'
            }
        }
        
        stage('test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('build') {
            steps {
                sh 'mvn package' 
            }
        }
    }

}
