pipeline {
    agent any
    tools { 
      maven 'jenkins-maven'
    }

    environment {
        registry = "hanv22011998/jenkins-demo"
        registryCredential = 'hanv22011998'
        dockerImage = ''
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/HaHust/jenkins-maven'
            }
        }
        
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
        }
        
        stage('build docker') {
            steps {
                script {
                    sh 'docker build -t $registry .'
                }
            }
        }

        stage('Push docker') {
            steps {
                script {
                    sh 'echo $registry'
//                     sh 'docker login -u $registryCredential -p $registryCredential'
//                     sh 'docker push $registry'
                }
            }
        }
    }

}
