pipeline {
    agent any
    tools { 
      maven 'jenkins-maven'
    }

    environment {
        registry = "hanv22011998/jenkins-demo"
        registryCredential = 'hanv22011998'
        registryPassword = 'Haqh1234'
        dockerImage = ''
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/HaHust/jenkins-maven'
            }
        }
        
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
        }
        
        stage('build docker') {
            steps {
                script {
                    sh 'docker build -t $registry .'
                }
            }
        }

        stage('Push docker') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_id', passwordVariable: 'pass', usernameVariable: 'username')]) {
                        sh "docker login -u ${username} -p ${pass}"
                    }
                    sh 'docker push $registry'
                }
            }
        }
    }
}
